version: '3.3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
