name: Check
defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MONGO_URL: ${{ secrets.MONGO_URL }}

jobs:
  check:
    name: Check on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os.runner }}
    defaults:
      run:
        shell: ${{ matrix.os.shell }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: macos-latest
            libmongocScript: ./scripts/setupOSX.sh
            shell: bash
          - runner: ubuntu-latest
            libmongocScript: ./scripts/setupUbuntu.sh
            shell: bash
          - runner: windows-latest
            libmongocScript: ./scripts/setupWindows.sh
            shell: C:\msys64\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}
    steps:
      - uses: actions/checkout@v2

      - name: Restore Gradle cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            scripts/build
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '${{ martix.os.libmongocScript }}') }}

      - name: Setup libmongoc
        run: ${{ matrix.os.libmongocScript }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle Check
        run: ./gradlew check

      - name: Gradle Compile
        run: ./gradlew compile assemble

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports-${{ matrix.os.runner }}
          path: |
            **/build/reports
