name: Check
defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MONGO_URL: ${{ secrets.MONGO_URL }}

jobs:
  check:
    name: Check on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os.runner }}
    defaults:
      run:
        shell: ${{ matrix.os.shell }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: macos-latest
            shell: bash
            libmongocScript: ./scripts/setupOSX.sh
          - runner: ubuntu-latest
            shell: bash
            libmongocScript: ./scripts/setupUbuntu.sh
          - runner: windows-latest
            shell: msys2 {0}
            libmongocScript: ./scripts/setupWindows.sh
    steps:
      - uses: msys2/setup-msys2@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          msystem: MINGW64
          update: true
          install: >-
            git

      - uses: actions/checkout@v2

      - name: Restore libmongoc cache
        id: cache-libmongoc
        uses: actions/cache@v2.1.6
        with:
          path: |
            scripts/build
          key: ${{ runner.os }}-libmongoc-${{ hashFiles(matrix.os.libmongocScript, './scripts/build/**') }}

      - name: Setup libmongoc
        run: ${{ matrix.os.libmongocScript }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Restore Gradle cache
        id: cache-gradle
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Gradle Compile
        run: ./gradlew compile assemble

      - name: Gradle Check
        run: ./gradlew check

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports-${{ matrix.os.runner }}
          path: |
            **/build/reports
