name: Sandbox
defaults:
  run:
    shell: msys2bash

on:
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MONGO_URL: ${{ secrets.MONGO_URL }}

jobs:
  check:
    runs-on: windows-latest
    steps:
      - run: echo bash
        shell: bash
      - run: echo WORKS!!!; pacman --noconfirm -Syu
        shell: C:\msys64\msys2_shell.cmd -use-full-path -mingw64 -no-start -here --norc -noprofile -e -o pipefail {0}
