name: Sandbox
defaults:
  run:
    shell: msys2bash

on:
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MONGO_URL: ${{ secrets.MONGO_URL }}

jobs:
  check:
    runs-on: windows-latest
    steps:
      - run: pacman -Syu
